export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  chilcdren: React.ReactNode
}) {
  return (
    <html clang="en">
      <body>{children}</body>
    </html>
  )
}
