// Note: We don't use the Select types here because they include MongoDB _id fields
// Instead, we define mock data as plain objects that match the Insert types

// Note: UserSelect is a Mongoose Document, so it will have _id, not id
// This is just for type reference - actual user will be created in seed.ts
export const mockUser = {
  name: "Test User",
  email: "test@example.com",
  emailVerified: new Date("2023-01-01T00:00:00Z"),
  age: 30,
  image: null,
  tradeStyle: "Test Style",
  totalAssetUsd: 100000,
  cryptoInvestmentUsd: 50000,
  walletAddress: "0xTestWalletAddress",
  riskTolerance: "medium",
  notificationEnabled: false,
} as const;

const now = new Date();

// Note: SignalSelect is a Mongoose Document, so it will have _id, not id
export const mockSignal = {
  tokenAddress: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  detectedAt: now,
  sources: [{ url: "https://x.com/OnchainLens/status/1921886124303380660", label: "Tweet by @OnchainLens" }],
  sentimentType: "negative" as const,
  suggestionType: "sell" as const,
  confidence: 0.8,
  rationaleSummary:
    "The tweet indicates a whale has deposited a significant amount of USDC ($40.5M) to increase short positions on BTC, ETH, and SOL, suggesting bearish sentiment towards these tokens, including SOL.",
  expiresAt: new Date(now.getTime() + 1000 * 60 * 60), // 1 hour from now
} as const;


export const mockTokenPrices = [
  {
    tokenAddress: "So11111111111111111111111111111111111111112",
    priceUsd: "168.48",//sol
    lastUpdated: new Date(),
    source: "jupiter",
  },
  {
    tokenAddress: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    priceUsd: "1.00",//usdc
    lastUpdated: new Date(),
    source: "jupiter",
  },
] as const;


// createdAt and updatedAt are auto-generated by timestamps option
export const mockTweets = [
  {
    authorId: "OnchainLens",
    url: "https://x.com/OnchainLens/status/1921886124303380660",
    content: `In the past 2 days, a whale has deposited $40.5M $USDC into #HypeLiquid to increase the short position on $BTC, $ETH, and $SOL with 5x leverage.

Address: 0x5b5d51203a0f9079f8aeb098a6523a13f298c060

Data
@nansen_ai`,
    replyCount: 5,
    retweetCount: 13,
    likeCount: 42,
    tweetTime: new Date("2025-05-12T18:50:02.570Z"),
    metadata: {},
  },
] as const;

// Note: UserBalanceSelect is a sub-schema embedded in User document
// It doesn't have id or userId fields - those are at the User level
export const mockUserBalances = [
  {
    tokenAddress: "So11111111111111111111111111111111111111112", // SOL
    balance: "2000",
    updatedAt: new Date("2023-01-01T06:00:00Z"),
  },
  {
    tokenAddress: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN", // JUP
    balance: "1000",
    updatedAt: new Date("2023-01-01T06:00:00Z"),
  },
] as const;
